[build]
  # No build command needed since this is a static site
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Cache control for HTML files
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Cache static assets for longer
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]  
  # Cache data files for shorter period
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# SPA-style routing fallback
[[redirects]]
  from = "/sleep/devices"
  to = "/sleep/devices/index.html"
  status = 200

[[redirects]]
  from = "/sleep/supplements"  
  to = "/sleep/supplements/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200