[build]
  publish = "."

[[redirects]]
  from = "/go/sleeplean"
  to   = "https://cf5ebf3dm3ebet5fu7lly4ni33.hop.clickbank.net/?tid=ssgsleeplean"
  status = 302
  force  = true

[[redirects]]
  from = "/go/*"
  to = "https://TRACKER.EXAMPLE/click?offer=:splat"
  status = 302
  force = true

[[redirects]]
  from = "/sleep/non-pill-solutions"
  to = "/sleep/non-pill-solutions/index.html"
  status = 200

[[redirects]]
  from = "/sleep/non-pill-solutions/"
  to = "/sleep/non-pill-solutions/index.html"
  status = 200

[[redirects]]
  from = "/sleep/supplements"
  to = "/sleep/supplements/index.html"
  status = 200

[[redirects]]
  from = "/sleep/supplements/"
  to = "/sleep/supplements/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200