[build]
  publish = "."

[[redirects]]
  from = "/sleep/non-pill-solutions"
  to = "/sleep/non-pill-solutions/index.html"
  status = 200

[[redirects]]
  from = "/sleep/non-pill-solutions/"
  to = "/sleep/non-pill-solutions/index.html"
  status = 200

[[redirects]]
  from = "/sleep/supplements"
  to = "/sleep/supplements/index.html"
  status = 200

[[redirects]]
  from = "/sleep/supplements/"
  to = "/sleep/supplements/index.html"
  status = 200

[[redirects]]
  from = "/pitch-black"
  to = "/pitch-black/index.html"
  status = 200

[[redirects]]
  from = "/pitch-black/"
  to = "/pitch-black/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200