[build]
  publish = "."

[[redirects]]
  from = "/sleep/devices"
  to = "/sleep/devices/index.html"
  status = 200

[[redirects]]
  from = "/sleep/devices/"
  to = "/sleep/devices/index.html"
  status = 200

[[redirects]]
  from = "/sleep/supplements"
  to = "/sleep/supplements/index.html"
  status = 200

[[redirects]]
  from = "/sleep/supplements/"
  to = "/sleep/supplements/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200